apiVersion: controller.kubeslice.io/v1alpha1
kind: Cluster
metadata:
  name: cluster-5
spec:
  networkInterface: eth0
  nodeIP: 11.11.11.70
  clusterProperty:
    telemetry:
      enabled: true
      telemetryProvider: "prometheus"
      endpoint: "http://10.1.1.27:8080"
    geoLocation:
    #  cloudProvider: "gcp"
      cloudRegion: "us-east-1"
    monitoring:
      kubernetesDashboard:
       # enabled: true
        #accessToken: "superSecretJWTToken"
        ingressPrefix: "/dashboard/"
