# permissions for end users to view sliceqosconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sliceqosconfig-viewer-role
rules:
- apiGroups:
  - controller.kubeslice.io
  resources:
  - sliceqosconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - controller.kubeslice.io
  resources:
  - sliceqosconfigs/status
  verbs:
  - get
