apiVersion: controller.kubeslice.io/v1alpha1
kind: SliceConfig
metadata:
  name: red
spec:
  sliceSubnet: 10.1.0.0/16
  sliceType: Application
  sliceGatewayProvider:
    sliceGatewayType: OpenVPN
    sliceCaType: Local
  sliceIpamType: Local
  clusters:
    - cluster-1
    - cluster-2
  qosProfileDetails:
    queueType: HTB
    priority: 1
    tcType: BANDWIDTH_CONTROL
    bandwidthCeilingKbps: 5120
    bandwidthGuaranteedKbps: 2560
    dscpClass: AF11
  externalGatewayConfig:
    - ingress:
        enabled: false
      egress:
        enabled: false
      nsIngress:
        enabled: false
      gatewayType: none
      clusters:
        - "*"
    - ingress:
        enabled: true
      egress:
        enabled: true
      nsIngress:
        enabled: true
      gatewayType: istio
      clusters:
        - cluster-2
  resourceQuotaProfile:
    sliceQuota:
      resources:
        memory: 32
        cpu: 100
      enforceQuota: true
    clusterQuota:
      - clusterName: cluster-1
        resources:
          memory: 16
          cpu: 50
        enforceQuota: true
        namespaceQuota:
          - namespace: namespace-1
            resources:
              memory: 8
              cpu: 25
            enforceQuota: true
      - clusterName: cluster-2
        resources:
          memory: 16
          cpu: 50
        enforceQuota: true
        namespaceQuota:
          - namespace: namespace-2
            resources:
              memory: 8
              cpu: 25
            enforceQuota: true
          - namespace: namespace-3
            resources:
              memory: 8
              cpu: 25
            enforceQuota: true